# Generated by Django 3.2.23 on 2023-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('publishDate', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
            ],
        ),
    ]
