# Generated by Django 3.2.23 on 2023-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='cover.jpg', upload_to='bookcovers'),
        ),
    ]
