# Generated by Django 3.2.23 on 2023-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopstore', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
