# Generated by Django 3.2.23 on 2023-11-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopstore', '0002_alter_book_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
